"""Initial migration

Revision ID: 58836fe13f59
Revises: 
Create Date: 2025-04-10 11:58:39.725400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58836fe13f59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_username'), ['username'], unique=True)

    op.create_table('bakery_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_da', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('name_de', sa.String(length=100), nullable=True),
    sa.Column('name_nl', sa.String(length=100), nullable=True),
    sa.Column('name_fi', sa.String(length=100), nullable=True),
    sa.Column('name_no', sa.String(length=100), nullable=True),
    sa.Column('name_sv', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cafe_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_da', sa.String(length=100), nullable=True),
    sa.Column('title_en', sa.String(length=100), nullable=True),
    sa.Column('title_de', sa.String(length=100), nullable=True),
    sa.Column('title_nl', sa.String(length=100), nullable=True),
    sa.Column('title_fi', sa.String(length=100), nullable=True),
    sa.Column('title_no', sa.String(length=100), nullable=True),
    sa.Column('title_sv', sa.String(length=100), nullable=True),
    sa.Column('description_da', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('description_nl', sa.Text(), nullable=True),
    sa.Column('description_fi', sa.Text(), nullable=True),
    sa.Column('description_no', sa.Text(), nullable=True),
    sa.Column('description_sv', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_da', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('name_de', sa.String(length=100), nullable=True),
    sa.Column('name_nl', sa.String(length=100), nullable=True),
    sa.Column('name_fi', sa.String(length=100), nullable=True),
    sa.Column('name_no', sa.String(length=100), nullable=True),
    sa.Column('name_sv', sa.String(length=100), nullable=True),
    sa.Column('description_da', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('description_nl', sa.Text(), nullable=True),
    sa.Column('description_fi', sa.Text(), nullable=True),
    sa.Column('description_no', sa.Text(), nullable=True),
    sa.Column('description_sv', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_da', sa.String(length=100), nullable=True),
    sa.Column('title_en', sa.String(length=100), nullable=True),
    sa.Column('title_de', sa.String(length=100), nullable=True),
    sa.Column('title_nl', sa.String(length=100), nullable=True),
    sa.Column('title_fi', sa.String(length=100), nullable=True),
    sa.Column('title_no', sa.String(length=100), nullable=True),
    sa.Column('title_sv', sa.String(length=100), nullable=True),
    sa.Column('description_da', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('description_nl', sa.Text(), nullable=True),
    sa.Column('description_fi', sa.Text(), nullable=True),
    sa.Column('description_no', sa.Text(), nullable=True),
    sa.Column('description_sv', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_number', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_booking_number'), ['booking_number'], unique=True)

    op.create_table('bakery_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mac_address', sa.String(length=20), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('num_participants', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mac_address', sa.String(length=20), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mac_address', sa.String(length=20), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bakery_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('bakery_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_item_id'], ['bakery_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['bakery_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bakery_order_item')
    op.drop_table('promotion_order')
    op.drop_table('event_registration')
    op.drop_table('bakery_order')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_booking_number'))

    op.drop_table('user')
    op.drop_table('promotion')
    op.drop_table('menu_item')
    op.drop_table('event')
    op.drop_table('cafe_hours')
    op.drop_table('bakery_item')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_username'))

    op.drop_table('admin')
    # ### end Alembic commands ###
